#!/usr/bin/env bash
# setup a nginx web server on our server + redirection + 404.
apt update -y && apt upgrade -y
apt install nginx -y

echo "Hello World!" >/var/www/html/index.nginx-debian.html

sed -i '/listen \[::\]:80 default_server;/a\        rewrite ^\/redirect_me https://www.youtube.com/watch?v=KfWAmnRWEKE permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >/var/www/html/404.html
sed -i '/KfWAmnRWEKE permanent;$/a\        error_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
