#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays "bad luck from China"
# after 4th line, "bad luck from Japan" after the 9th line, and
# "bad luck from Italy" after the 17th line

i=1
while [ $i -le 20 ]; do
	echo $i

	case $i in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
	esac

	((i++))
done
